# Generated by Django 5.2.1 on 2025-06-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_department_department_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='date_of_birth',
            new_name='employee_date_of_birth',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='date_of_joining',
            new_name='employee_date_of_joining',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='employee_department',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='email',
            new_name='employee_email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='employee_first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='last_name',
            new_name='employee_last_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='phone_number',
            new_name='employee_phone_number',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='salary',
            new_name='employee_salary',
        ),
        migrations.RemoveField(
            model_name='department',
            name='department_location',
        ),
        migrations.RemoveField(
            model_name='department',
            name='department_phone_number',
        ),
        migrations.AddField(
            model_name='department',
            name='department_employees',
            field=models.ManyToManyField(blank=True, related_name='departments', to='api.employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='department_revenue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_position',
            field=models.CharField(default='Employee', max_length=100),
        ),
    ]
